### ISSUE TITLE
next7.3后插件报错

### ISSUE THREAD

**Issue by fengbrute** [Gisonrg/hexo-github-card#6]
非常感谢作者能写出这么方便美观的插件，最近hexo主题next由5.x升级到了7.3，插件能显示，但是报错，报错如图，不知道是否是插件问题，还是hexo版本和next主题问题，希望您能抽出时间看下，万分感谢
hexo: 3.9.0
theme: next 7.3
chrome: ![](https://qn.peri-nas.top/20190820120717.png)
![报错](https://qn.peri-nas.top/20190820120339.png)
![](https://qn.peri-nas.top/20190820120516.png)

**Comment by Gisonrg** [comment]
哈喽
不好意思 我这边不能reproduce你的issue 包括使用最新的hexo和next版本
从error来看貌似是next的问题？如果你有link的话我可以再帮你看看

**Comment by hooray** [comment]
执行 `hexo s` 后报错
```
Template render error: (unknown path)
  Error: template not found: card.html
    at Object._prettifyError (D:\testblog\node_modules\nunjucks\src\lib.js:36:11)
    at D:\testblog\node_modules\nunjucks\src\environment.js:567:19
    at eval (eval at _compile (D:\testblog\node_modules\nunjucks\src\environment.js:637:18), <anonymous>:11:11)
    at tryCatcher (D:\testblog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\testblog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (D:\testblog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (D:\testblog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (D:\testblog\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (D:\testblog\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (D:\testblog\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (D:\testblog\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues (D:\testblog\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:439:21)
error Command failed with exit code 2.
```

**Comment by hooray** [comment]
hexo: 4.2.0
theme: next 7.6.0
