### ISSUE TITLE
运行直接报错

### ISSUE THREAD

**Issue by hooray** [Gisonrg/hexo-github-card#8]
执行`hexo s`后报错
```
Template render error: (unknown path)
  Error: template not found: card.html
    at Object._prettifyError (D:\testblog\node_modules\nunjucks\src\lib.js:36:11)
    at D:\testblog\node_modules\nunjucks\src\environment.js:567:19
    at eval (eval at _compile (D:\testblog\node_modules\nunjucks\src\environment.js:637:18), <anonymous>:11:11)
    at tryCatcher (D:\testblog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\testblog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (D:\testblog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (D:\testblog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (D:\testblog\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (D:\testblog\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (D:\testblog\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (D:\testblog\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues (D:\testblog\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:439:21)
error Command failed with exit code 2.
```
hexo: 4.2.0
theme: next 7.6.0

**Comment by fengbrute** [comment]
报错，同上，版本的hexo和next
![image](https://user-images.githubusercontent.com/20437275/75944828-a0605680-5ed3-11ea-918f-3841e86664f0.png)
![image](https://user-images.githubusercontent.com/20437275/75944857-b110cc80-5ed3-11ea-8345-2c526d8a58d4.png)

**Comment by Gisonrg** [comment]
@hooray
@fengbrute

刚试图修复了这个错误，应该是文件路径的问题，你们试试install hexo-github-card@1.0.4版本?

**Comment by fengbrute** [comment]
刚才试了你说的，好像还是不行
![image](https://user-images.githubusercontent.com/20437275/76161018-3f05e500-616a-11ea-97ec-5b78d9e41fe3.png)

![image](https://user-images.githubusercontent.com/20437275/76161010-2990bb00-616a-11ea-9388-b1488485b4d7.png)

**Comment by Gisonrg** [comment]
@fengbrute 
有没有试过先
```
hexo clean
```
然后再
```
hexo s
```

如果还是报错的话，可否看看错误信息中`node_modules\hexo-github-card\card.html`这个文件是否存在？再或者 新开一个hexo project重新装这个包试试？

目前在mac和ubuntu上貌似我都不能reproduce，我这周找时间用windows再试试，不好意思呀

**Comment by fengbrute** [comment]
我想大概率是插件和新的`next 7.7.2`主题兼容出了问题。
我新建了一个`hexo` project，并且使用最新的`next`主题
![image](https://user-images.githubusercontent.com/20437275/76177182-5d152900-61ee-11ea-9ea6-84be3bf021a2.png)
安装插件后编译不通过，
![image](https://user-images.githubusercontent.com/20437275/76177262-99e12000-61ee-11ea-8d9e-3d8782151ec3.png)
![image](https://user-images.githubusercontent.com/20437275/76177336-dc0a6180-61ee-11ea-9aaa-49c768c104ec.png)
但是，不使用`next`主题，使用默认的`landscape`主题，重新`hexo clean`后可以通过编译

**Comment by hooray** [comment]
应该和 next 的版本有关，我也是升级 next 后就不行了，我的临时解决办法就是把 card.html 在 index.js 里直接通过反单引号直接拼接模版字符串

**Comment by Gisonrg** [comment]
@hooray @fengbrute 
感谢帮分析debug，我这周末试试看能不能修好

**Comment by hooray** [comment]
@Gisonrg 好的，麻烦你辣~

**Comment by Gisonrg** [comment]
@hooray @fengbrute 
我发现可能是我用来渲染模板的[nunjucks](https://github.com/mozilla/nunjucks)版本问题，参考了一下其它的hexo plugin,把nunjucks版本降回到2.X解决了这个问题。具体原因估计是新版本的nunjucks与Next主题的模板渲染冲突吧
已经更新 `hexo-github-card@1.0.5`了，你们可以试试

本地测试通过
![image](https://user-images.githubusercontent.com/4332224/76676474-d2be3200-65fe-11ea-854f-a8ec07f053dd.png)

` npm list --depth=0`

![image](https://user-images.githubusercontent.com/4332224/76676478-e073b780-65fe-11ea-87f1-6c536c7e025f.png)

再次感谢提这个issue, 如果还有问题欢迎reopen :)
